name: 06 Passing Data between Steps

on:
  workflow_dispatch: 
       
jobs:
  data-passing:
    runs-on: ubuntu-latest 
    steps:
      - name: Create data 
        id: sender
        run: |
            echo "name=Simikahle">> $GITHUB_OUTPUT
        

      - name: List space again
        run: |
            echo ${{steps.sender.outputs.name}}
